name: Node.js CI

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: ./reusable-workflow-repo
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout reusable workflow dir
      uses: actions/checkout@v3
      with:
        repository: early-steps/.github
        path: ./reusable-workflow-repo
    - name: Checkout code
      uses: actions/checkout@v3


    # Common steps for both 'main', 'release' and 'develop' branches and PRs
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - name: Install dependencies
    #   run: npm ci
    # - name: Run shell scripts
    #   run: |
    #     echo "${{ github.action_path }}"
    #     ${{ github.action_path }}/.github/workflows/script.sh
    #     shell: bash
    - name: Make the script files executable
      run: |
        echo "current dir"
        ls
        echo "going back"
        cd ..
        echo "current dir"
        ls
        echo "going back"
        cd ..
        echo "current dir"
        ls
        echo "going in"
        cd admin_portal
        echo "current dir"
        ls
        echo "going in"
        cd admin_portal
        echo "current dir"
        ls
        # chmod +x ./reusable-workflow-repo/.github/workflows/script.sh
    # - name: Run shell scripts
    #   run: |
    #     ./reusable-workflow-repo/.github/workflows/script.sh

    

    # - name: Run test cases
    #   run: npm run test

    # - name: Build
    #   run: npm run build

    #configure aws credentials
    # - name: Configure AWS credentials
    #   if: github.ref == 'refs/heads/main'
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     role-to-assume: arn:aws:iam::867558014338:role/github-actions-oidc
    #     aws-region: us-east-1
    
    # # code pushed in develop
    # - name: Conditional step for commit in develop branch
    #   if: github.ref == 'refs/heads/develop'
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: deploy --stage dev

    # # code pushed in release
    # - name: Conditional step for commit in release branch
    #   if: github.ref == 'refs/heads/release'
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: deploy --stage uat
    
    # # code pushed in main
    # - name: Conditional step for commit in main branch
    #   if: github.ref == 'refs/heads/main'
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: deploy --stage prod
